openapi: 3.0.3
info:
  title: Aluno
  description: Alunos de graduação da UnB
  termsOfService: http://api.redes.unb.br/terms
  contact:
    email: ricardo.puttini@gmail.com
  license:
    name: Apache 2.0
    url: http://www.apache.org/licenses/LICENSE-2.0.html
  version: 1.0.0
servers:
  - url: https://api.redes.unb.br/api/Aluno
tags:
  - name: Aluno
    description: Alunos de graduação da UnB
paths:
  /:
    get:
      tags:
        - Aluno
      summary: Pesquisar alunos
      description: Pesquisar alunos por ...
      operationId: search
      parameters:
        - name: nome
          in: query
          description: nome ou parte do nome do aluno
          required: false
          schema:
            type: string
        - name: unidade
          in: query
          description: código da unidade
          required: false
          schema:
            type: string
        - name: curso
          in: query
          description: código do curso
          required: false
          schema:
            type: string
        - name: periodoIngresso.ano
          in: query
          description: ano de ingresso
          required: false
          schema:
            type: integer
            minimum: 2000
            maximum: 2040
        - name: periodoIngresso.periodo
          in: query
          description: número do período letivo de ingresso do aluno
          required: false
          schema:
            type: integer
            minimum: 1
            maximum: 2
        - name: size
          in: query
          description: tamanho da página (número de registros por página)
          required: false
          schema:
            type: string
        - name: offset
          in: query
          description: posicao do primerio registro da página (primeiro registro _offset=0)
          required: false
          schema:
            type: string
      responses:
        '200':
          description: Successful operation
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/AlunoSearchSet'        
  /{id}:
    get:
      tags:
        - Aluno
      summary: Consultar um aluno
      description: Consulta um aluno pelo número de matrícula (id)
      operationId: read
      parameters:
        - name: id
          in: path
          description: matrícula do aluno
          required: true
          schema:
            type: string
      responses:
        '200':
          description: Successful operation
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Aluno'          
        '404':
          description: not found
components:
  schemas:
    Resource:
      type: object
      properties:
        '@type':
          type: string
          enum:
            - Disciplina
            - Aluno
            - Curso
            - Matricula
            - EstruturaCurricular
            - Turma
            - Historico
          example: Aluno  
        id:  
          type: string
          example: "180012345"
    Resource_Curso:
      type: object
      properties:
        '@type':
          type: string
          enum:
            - Disciplina
            - Aluno
            - Curso
            - Matricula
            - EstruturaCurricular
            - Turma
            - Historico
          example: Curso  
        id:  
          type: string
          example: "6351"
    SearchSet:
      type: object
      properties:
        total:
          type: integer
          minimum: 0
          example: 11
        size:
          type: integer
          minimum: 1
          example: 10
        offset:
          type: integer
          minimum: 0
          example: 10
        links:
          type: object
          properties:
            self:
              type: string
              example: Aluno?size=10&offset=10
            next:
              type: string
              example: Aluno?size=10&offset=20
            previous:
              type: string
              example: Aluno?size=10
          required:
          - self
      required:
      - total
    Aluno:
      type: object
      allOf:
      - $ref: '#/components/schemas/Resource'
      - type: object
        properties:
          matricula:
            type: string
            example: "180012345"
          nome:
            type: string
            example: ADA LOVELACE
          curriculo:
            type: string
            example: Curriculo/6351.2
          ira:
            type: number
            example: 4.35
          curso:
            $ref: '#/components/schemas/CursoShort'  
          periodoIngresso:
            $ref: '#/components/schemas/PeriodoLetivo'  
    AlunoShort:
      type: object
      allOf:
      - $ref: '#/components/schemas/Resource'
      - type: object
        properties:
          matricula:
            type: string
            example: "180012345"
          nome:
            type: string
            example: ADA LOVELACE
    PeriodoLetivo:
      type: object
      properties:
        ano:
          type: integer
          minimum: 2000
          maximum: 2040
          example: 2024
        periodo:
          type: integer
          minimum: 1
          maximum: 2
    AlunoSearchSet:
      type: object
      allOf:
      - $ref: '#/components/schemas/SearchSet'
      - type: object
        properties:
          values:
            type: array
            items:
              $ref: '#/components/schemas/AlunoShort'
    CursoShort:
      type: object
      allOf:
      - $ref: '#/components/schemas/Resource_Curso'
      - type: object
        properties:
          codigo:
            type: string
            example: '6351'
          nome:
            type: string
            example: ENGENHARIA DE REDES DE COMUNICAÇÃO          